version: "3.0"

services:
    eduard-ipc127e:
        image: eduartrobotik/eduart-perception-ipc127e:0.1.0
        container_name: eduart-perception-ipc127e-0.1.0
        user: user
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard/red
        network_mode: "host"
#        networks:
#            - multi-robot
#            - robot-eduard
        devices:
            - '/dev:/dev'

networks:
    multi-robot:
        name: "multi-robot"
        external: true
    robot-eduard:
        name: "robot-eduard"
