/**:
  ros__parameters:
    use_sim_time: false
    frame_id: object_sensor/front
    frame_id_object_origin: eduard/blue/base_link

    camera:
      fps: 10.0
      height: 400
      width: 1280
      device: '192.168.3.110'

    filter:
      orientation:
        weight: 0.3
      position:
        weight: 0.4

    qr_code_detector:
      qr_code_text_filter: eduard
      roi_increase_rate:
        horizontal: 0.4
        vertical: 0.2
