/**:
  ros__parameters:
    use_sim_time: false
    frame_id: object_sensor/front

    camera:
      fps: 10.0
      height: 400
      width: 1280

    qr_code_detector:
      qr_code_text_filter: Eduard
      roi_increase_rate:
        horizontal: 0.4
        vertical: 0.2
