version: "3.0"

services:
  eduart-swarm-master:
    image: eduartrobotik/eduart-perception:0.2.0
    container_name: eduart-perception-0.2.0
    user: user
    restart: always
    privileged: true
    ipc: host
    pid: host
    mem_limit: 300mb
    environment:
        - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
    network_mode: "host"
    command: bash -c 'cd /home/user/ros/launch_content; ros2 launch qr_code_detection_and_pose_estimation.launch.py'
    volumes:
        - './launch_content:/home/user/ros/launch_content:r'
